spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/product_database
    username: postgres # substitua pelo seu nome de usuário do PostgreSQL
    password: 123
  jpa:
    hibernate:
      ddl-auto: update # ou create, create-drop, none, dependendo da sua necessidade
    show-sql: true
springdoc:
  swagger-ui:
    use-root-path: true

api:
  key: 1234
